version: "3.0"
services:
  pintos:
    command: bash -c "sleep infinity"
    build: .
    environment:
        - TERM=xterm-256color
    volumes:
      - ./env/.bashrc:/root/.bashrc
      - ./env/sources.list:/etc/apt/sources.list
      - ./workspace:/root/workspace