version: "3.0"
services:
  pintos:
    command: 
      bash -c "
      apt update
      && apt -y install make
      && apt -y install vim
      && apt -y install gcc-4.4
      && apt -y install gdb
      && cd root/workspace/bochs-2.6.2 && make install
      && ((ls /usr/bin/gcc-4.4 >> /dev/null 2>&1 && mv /usr/bin/gcc-4.4 /usr/bin/gcc) || echo empty)
      && sleep infinity
      "
    build: .
    environment:
        - TERM=xterm-256color
    volumes:
      - ./env/.bashrc:/root/.bashrc
      - ./env/sources.list:/etc/apt/sources.list
      - ./workspace:/root/workspace